apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap 
  namespace: flaskapp-ns
data:
  MYSQL_DATABASE: flask_db
  MYSQL_HOST: mysql-sts-0.mysql-svc.flaskapp-ns.svc.cluster.local
  MYSQL_USER: root
  MYSQL_DB: flask_db
